name: CI/CD Pipeline Deploy to Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get GitHub Action's IP
      - name: Get GitHub Action IP
        id: ip
        uses: haythem/public-ip@v1.2

      # Step 2: Add GitHub Actions IP to Security Group
      - name: Add GitHub Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Step 3: Deploy to the Laravel + Vite Application Server
      - name: Deploy to Prod Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /var/www/laravel_deployment

            # Ensure the latest code is pulled
            git stash
            git pull origin main

            # Install PHP dependencies
            composer install --no-dev --optimize-autoloader

            # Run database migrations
            php artisan migrate --force

            # Install and build frontend assets with Vite
            npm install
            npm run build

            # Clear and cache Laravel configuration
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Ensure correct permissions for storage and cache
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            # Restart PHP-FPM
            sudo systemctl restart php8.1-fpm
            sudo systemctl restart nginx

      # Step 4: Remove GitHub Actions IP from Security Group
      - name: Remove GitHub Actions IP from Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ secrets.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        if: always()
